/**
 * 빌드 전 HTML 파일들을 TypeScript 모듈로 변환
 * public/*.html → src/pages.ts (export const pages = {...})
 */
import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

const files = {
  index: 'public/index.html',
  portfolio: 'public/portfolio.html',
  portfolioV1: 'public/portfolio-v1.html',
  threshold: 'public/threshold.html',
  brandVoice: 'public/brand-voice.html',
  flowchart: 'public/flowchart.html',
  planning: 'public/planning.html',
}

const entries = Object.entries(files).map(([key, path]) => {
  const content = readFileSync(resolve(root, path), 'utf-8')
  const escaped = JSON.stringify(content)
  return `  ${key}: ${escaped}`
})

const output = `// AUTO-GENERATED by scripts/embed-html.mjs — DO NOT EDIT
export const pages: Record<string, string> = {
${entries.join(',\n')}
}
`

writeFileSync(resolve(root, 'src/pages.ts'), output, 'utf-8')
console.log('✅ HTML pages embedded into src/pages.ts')
